### ISSUE TITLE
Alternate Item and Block Data Method

### ISSUE THREAD

**Issue by Nerdpie** [maruohon/tellme#1]
Sorry about the title; couldn't think of anything better.  Any way, I've gotten used to using `/mt hand` and `/mt blockinfo` in packs that have MineTweaker.  The "hand" subcommand write the held item's ID (e.g. `<minecraft:stick>`), NBT, and ore dictionary information to the chat and to the minetweaker.log file; it also places the item's ID and NBT tags into the user's clipboard.  The "blockinfo" subcommand toggles similar behavior for right-clicking on blocks.

I haven't looked into the available Forge hooks, so I don't know if similar functionality is possible at present, but I thought that I'd mention it.  My main concern is a mix of convenience and mod interactions; what happens if, for instance, another mod needs the player to right-click a block with a gold nugget?  I also remember having some mod make clicking blocks with a stick print debug info; that got annoying due to clicking without thinking about what was in my hand.

Overall, this isn't a major issue, but I thought I'd mention it.  The mod looks useful, and I'll definitely be trying it out.

**Comment by maruohon** [comment]
So are you basically asking for something like a config option to disable the gold nugget and blaze rod debug functionality (or maybe change the items used for them?), and add command alternatives for them? That seems like a good idea and I will probably do that.

However, what I'm confused about is that you are concerned about mod interactions. But do you mean that while trying to debug something, and if a block needs right clicking with a gold nugget? Because in regular game-play there should be no point in having this mod even installed... right? And for non-OP players the debug items shouldn't even do anything, nor do the commands.

**Comment by Nerdpie** [comment]
Point taken.  I've not actually tried the mod yet, rather these things came to mind based off of the mod description and past experiences; for instance, I've seen a number of packs where lots of extra debug information is left on, such as all of the ore dictionary entries, the unlocalized names, and more showing in NEI and similar.  But yes, in general gameplay, the mod shouldn't be needed.  ... though I sometimes would use the MineTweaker commands on a whim, but I'm not exactly the average player.

Ultimately, it's your mod, so your call, but the config settings sound reasonable.
