### ISSUE TITLE
Suggestion: A command that lists all crops/growables

### ISSUE THREAD

**Issue by katubug** [maruohon/tellme#20]
Hi! I'm working on a project that involves getting a full list of all the crops in the pack. I've tried using CraftTweaker's `/ct seed` command, but it produces an incomplete list, because in many cases, the seeds are also the end product.

I am not sure if this is possible, or if you are still maintaining the 1.12 version, but I thought I would ask. Thank you very much for your time!

**Comment by maruohon** [comment]
Looks like I added an `items-plantable` dump in September, which returns a list of all items that implement the Forge `IPlantable` interface. That build is not on CurseForge though, it's only on my server here: https://masa.dy.fi/tmp/minecraft/mods/tellme/tellme-1.12.2-0.7.0-dev.20190926.172157.jar

I don't know if this covers what you need? Also not sure how accurate the Plant Type info is going to be, since the method to query that takes in a world and block position, which the dump method doesn't have, so it just gives it the overworld 0, 0, 0 position... So if any modded item/block actually checks something from the world, they would get it wrong.

**Comment by katubug** [comment]
Hi! Yeah, this should be fine! It doesn't have to be completely perfect, I can always patch this project later if I miss something. Thank you very much for the link!
