### ISSUE TITLE
No /tellme command in multiplayer (latest 1.19 build, running 1.19.2)

### ISSUE THREAD

**Issue by sudofox** [maruohon/tellme#31]
EDIT: It seems that the command is unavailable in multiplayer, but does show up in singleplayer. I edited the issue title to reflect that.

/tellme does not autofill, and trying to run it returns a command not found error.

version 0.9.0-beta.1, running on Fabric, MC 1.19.2

It does show up fine in ModMenu, and I don't see any logs related to it in my console.

**Comment by maruohon** [comment]
The 1.14+ versions currently only work if the mod is (also) on the logical server side. Which means that you can't currently use it on the client side only if you are on a server. The server would also need to have the mod in any multiplayer scenario. (The client doesn't *need it*, but the command completions/suggestions would not all work without the mod also on the client.) It should always work in single player though.

**Comment by sudofox** [comment]
I see, I suppose that makes sense. Indeed, perhaps the issue is just one of my own expectations. Having gone through the readme to look at the documentation after reading your comment, I now see that this behavior is indeed documented, so it's just my own personal issue. Thanks for clearing that up for me!

**Comment by maruohon** [comment]
I do possibly intend to allow using it on the client as well. The main issue with that is how much of the command code would need to change to support that, since in that case one of the arguments you get is different than on the server case. Plus you wouldn't have a MinecraftServer instance available, so a bunch of the stuff wouldn't even work in that case. I still haven't gotten around to looking into how much work and changes that would require. It's rather low on my priority list.
